import type { NavSection } from "@/lib/nav/types";

export const NAV_SECTIONS: NavSection[] = [
  {
    key: "core",
    label: "Core",
    items: [
      {
        key: "dashboard",
        label: "Dashboard",
        href: "/dashboard",
        visibilityByPersona: {
          PROJECT_OWNER: "VISIBLE",
          INVESTOR: "VISIBLE",
          CARBON_TRADER: "VISIBLE",
          ADMIN: "VISIBLE",
        },
        description: "Your overview and next actions",
      },
    ],
  },
  {
    key: "projects",
    label: "Projects",
    items: [
      {
        key: "projectOwner",
        label: "Project Owner Portal",
        href: "/owner",
        visibilityByPersona: {
          PROJECT_OWNER: "VISIBLE",
          INVESTOR: "GATED",
          CARBON_TRADER: "HIDDEN",
          ADMIN: "VISIBLE",
        },
        description: "Create projects and manage dataroom readiness",
      },
      {
        key: "ownerProjects",
        label: "Project Pipeline",
        href: "/owner/projects",
        visibilityByPersona: {
          PROJECT_OWNER: "VISIBLE",
          INVESTOR: "HIDDEN",
          CARBON_TRADER: "HIDDEN",
          ADMIN: "VISIBLE",
        },
        description: "View and edit project portfolio",
      },
      {
        key: "ownerProjectNew",
        label: "Create New Project",
        href: "/owner/projects/new",
        visibilityByPersona: {
          PROJECT_OWNER: "VISIBLE",
          INVESTOR: "HIDDEN",
          CARBON_TRADER: "HIDDEN",
          ADMIN: "VISIBLE",
        },
        description: "Launch seven-step project wizard",
      },
      {
        key: "ownerDocuments",
        label: "Document Library",
        href: "/owner/documents",
        visibilityByPersona: {
          PROJECT_OWNER: "VISIBLE",
          INVESTOR: "HIDDEN",
          CARBON_TRADER: "HIDDEN",
          ADMIN: "VISIBLE",
        },
        description: "Manage dataroom metadata and visibility",
      },
      {
        key: "ownerMessages",
        label: "Diligence Messages",
        href: "/owner/messages",
        visibilityByPersona: {
          PROJECT_OWNER: "VISIBLE",
          INVESTOR: "HIDDEN",
          CARBON_TRADER: "HIDDEN",
          ADMIN: "VISIBLE",
        },
        description: "Respond to investor Q and A",
      },
      {
        key: "ownerTasks",
        label: "Owner Tasks",
        href: "/owner/tasks",
        visibilityByPersona: {
          PROJECT_OWNER: "VISIBLE",
          INVESTOR: "HIDDEN",
          CARBON_TRADER: "HIDDEN",
          ADMIN: "VISIBLE",
        },
        description: "Operational readiness task queue",
      },
      {
        key: "ownerSettings",
        label: "Owner Settings",
        href: "/owner/settings",
        visibilityByPersona: {
          PROJECT_OWNER: "VISIBLE",
          INVESTOR: "HIDDEN",
          CARBON_TRADER: "HIDDEN",
          ADMIN: "VISIBLE",
        },
        description: "Portal and profile configuration",
      },
      {
        key: "investor",
        label: "Investor Portal",
        href: "/investor",
        visibilityByPersona: {
          PROJECT_OWNER: "GATED",
          INVESTOR: "VISIBLE",
          CARBON_TRADER: "GATED",
          ADMIN: "VISIBLE",
        },
        description: "Search, underwrite, diligence, invest",
      },
      {
        key: "investorSearch",
        label: "Market Search",
        href: "/investor/search",
        visibilityByPersona: {
          PROJECT_OWNER: "GATED",
          INVESTOR: "VISIBLE",
          CARBON_TRADER: "GATED",
          ADMIN: "VISIBLE",
        },
        description: "Filter and rank opportunities",
      },
      {
        key: "investorCompare",
        label: "Compare Set",
        href: "/investor/compare",
        visibilityByPersona: {
          PROJECT_OWNER: "HIDDEN",
          INVESTOR: "VISIBLE",
          CARBON_TRADER: "HIDDEN",
          ADMIN: "VISIBLE",
        },
        description: "Compare shortlisted projects",
      },
      {
        key: "investorWatchlist",
        label: "Watchlist",
        href: "/investor/watchlist",
        visibilityByPersona: {
          PROJECT_OWNER: "HIDDEN",
          INVESTOR: "VISIBLE",
          CARBON_TRADER: "HIDDEN",
          ADMIN: "VISIBLE",
        },
        description: "Track saved opportunities",
      },
      {
        key: "investorMandate",
        label: "Investment Mandate",
        href: "/investor/mandate",
        visibilityByPersona: {
          PROJECT_OWNER: "HIDDEN",
          INVESTOR: "VISIBLE",
          CARBON_TRADER: "HIDDEN",
          ADMIN: "VISIBLE",
        },
        description: "Set diligence and funding criteria",
      },
      {
        key: "investorMessages",
        label: "Investor Messages",
        href: "/investor/messages",
        visibilityByPersona: {
          PROJECT_OWNER: "HIDDEN",
          INVESTOR: "VISIBLE",
          CARBON_TRADER: "HIDDEN",
          ADMIN: "VISIBLE",
        },
        description: "Diligence communications and responses",
      },
    ],
  },
  {
    key: "trading",
    label: "Trading",
    items: [
      {
        key: "market",
        label: "Carbon Trading (RFQ)",
        href: "/trading",
        visibilityByPersona: {
          PROJECT_OWNER: "GATED",
          INVESTOR: "VISIBLE",
          CARBON_TRADER: "VISIBLE",
          ADMIN: "VISIBLE",
        },
        description: "Listings, RFQs, quotes, OTC DvP settlement",
      },
      {
        key: "tradingMarketplace",
        label: "Market",
        href: "/trading/marketplace",
        visibilityByPersona: {
          PROJECT_OWNER: "GATED",
          INVESTOR: "VISIBLE",
          CARBON_TRADER: "VISIBLE",
          ADMIN: "VISIBLE",
        },
        description: "Listings and indicative pricing",
      },
      {
        key: "tradingRfq",
        label: "RFQ",
        href: "/trading/rfq/new",
        visibilityByPersona: {
          PROJECT_OWNER: "HIDDEN",
          INVESTOR: "VISIBLE",
          CARBON_TRADER: "VISIBLE",
          ADMIN: "VISIBLE",
        },
        description: "Create request for quote",
      },
      {
        key: "tradingQuotes",
        label: "Negotiations / Quotes",
        href: "/trading/quotes",
        visibilityByPersona: {
          PROJECT_OWNER: "HIDDEN",
          INVESTOR: "VISIBLE",
          CARBON_TRADER: "VISIBLE",
          ADMIN: "VISIBLE",
        },
        description: "Quote book and acceptance flow",
      },
      {
        key: "tradingTrades",
        label: "Settlement",
        href: "/trading/trades",
        visibilityByPersona: {
          PROJECT_OWNER: "HIDDEN",
          INVESTOR: "VISIBLE",
          CARBON_TRADER: "VISIBLE",
          ADMIN: "VISIBLE",
        },
        description: "Trade lifecycle and milestones",
      },
      {
        key: "tradingPositions",
        label: "Wallet",
        href: "/trading/positions",
        visibilityByPersona: {
          PROJECT_OWNER: "HIDDEN",
          INVESTOR: "VISIBLE",
          CARBON_TRADER: "VISIBLE",
          ADMIN: "VISIBLE",
        },
        description: "Holdings and inventory positions",
      },
      {
        key: "tradingRetirements",
        label: "Retirement",
        href: "/trading/retirements",
        visibilityByPersona: {
          PROJECT_OWNER: "HIDDEN",
          INVESTOR: "VISIBLE",
          CARBON_TRADER: "VISIBLE",
          ADMIN: "VISIBLE",
        },
        description: "Retire credits and certificates",
      },
    ],
  },
  {
    key: "onboarding",
    label: "Onboarding",
    items: [
      {
        key: "onboardingUser",
        label: "Client Onboarding",
        href: "/onboarding",
        visibilityByPersona: {
          PROJECT_OWNER: "VISIBLE",
          INVESTOR: "VISIBLE",
          CARBON_TRADER: "VISIBLE",
          ADMIN: "VISIBLE",
        },
        description: "KYC/AML, trading enablement, permissions",
      },
      {
        key: "onboardingStart",
        label: "Onboarding Start",
        href: "/onboarding/start",
        visibilityByPersona: {
          PROJECT_OWNER: "VISIBLE",
          INVESTOR: "VISIBLE",
          CARBON_TRADER: "VISIBLE",
          ADMIN: "VISIBLE",
        },
        description: "Select onboarding journey",
      },
      {
        key: "onboardingInstitution",
        label: "New Institution",
        href: "/onboarding/institution/new",
        visibilityByPersona: {
          PROJECT_OWNER: "VISIBLE",
          INVESTOR: "VISIBLE",
          CARBON_TRADER: "VISIBLE",
          ADMIN: "VISIBLE",
        },
        description: "Institution KYC application",
      },
      {
        key: "onboardingPerson",
        label: "New User",
        href: "/onboarding/person/new",
        visibilityByPersona: {
          PROJECT_OWNER: "VISIBLE",
          INVESTOR: "VISIBLE",
          CARBON_TRADER: "VISIBLE",
          ADMIN: "VISIBLE",
        },
        description: "Personal onboarding and verification",
      },
    ],
  },
  {
    key: "admin",
    label: "Administration",
    items: [
      {
        key: "adminDashboard",
        label: "Admin Command Centre",
        href: "/admin/dashboard",
        visibilityByPersona: {
          PROJECT_OWNER: "HIDDEN",
          INVESTOR: "HIDDEN",
          CARBON_TRADER: "HIDDEN",
          ADMIN: "VISIBLE",
        },
        description: "Tasks, SLAs, risk, oversight",
      },
      {
        key: "adminOnboarding",
        label: "Onboarding Operations",
        href: "/admin/onboarding",
        visibilityByPersona: {
          PROJECT_OWNER: "HIDDEN",
          INVESTOR: "HIDDEN",
          CARBON_TRADER: "HIDDEN",
          ADMIN: "VISIBLE",
        },
        description: "Case queue, reviews, policy checks",
      },
      {
        key: "adminRisk",
        label: "Risk",
        href: "/admin/risk",
        visibilityByPersona: {
          PROJECT_OWNER: "HIDDEN",
          INVESTOR: "HIDDEN",
          CARBON_TRADER: "HIDDEN",
          ADMIN: "VISIBLE",
        },
        description: "Risk queue and escalations",
      },
      {
        key: "adminTrading",
        label: "Trading Oversight",
        href: "/admin/trading",
        visibilityByPersona: {
          PROJECT_OWNER: "HIDDEN",
          INVESTOR: "HIDDEN",
          CARBON_TRADER: "HIDDEN",
          ADMIN: "VISIBLE",
        },
        description: "RFQ, trade, and dispute supervision",
      },
      {
        key: "adminDisputes",
        label: "Disputes",
        href: "/admin/disputes",
        visibilityByPersona: {
          PROJECT_OWNER: "HIDDEN",
          INVESTOR: "HIDDEN",
          CARBON_TRADER: "HIDDEN",
          ADMIN: "VISIBLE",
        },
        description: "Dispute escalation and resolution",
      },
      {
        key: "adminTasks",
        label: "Admin Tasks",
        href: "/admin/tasks",
        visibilityByPersona: {
          PROJECT_OWNER: "HIDDEN",
          INVESTOR: "HIDDEN",
          CARBON_TRADER: "HIDDEN",
          ADMIN: "VISIBLE",
        },
        description: "Operational queue and assignment",
      },
      {
        key: "adminSla",
        label: "SLA Monitor",
        href: "/admin/sla",
        visibilityByPersona: {
          PROJECT_OWNER: "HIDDEN",
          INVESTOR: "HIDDEN",
          CARBON_TRADER: "HIDDEN",
          ADMIN: "VISIBLE",
        },
        description: "SLA breach tracking and response",
      },
      {
        key: "adminDocuments",
        label: "Documents",
        href: "/admin/documents",
        visibilityByPersona: {
          PROJECT_OWNER: "HIDDEN",
          INVESTOR: "HIDDEN",
          CARBON_TRADER: "HIDDEN",
          ADMIN: "VISIBLE",
        },
        description: "Policy and evidence documentation",
      },
    ],
  },
];
